---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers



- name: configuration
  hosts: all
  become: yes
  roles:
    - {name: configuration}

- name: deploy haproxy
  hosts: frontends
  become: yes
  roles:
    - {name: frontend-tier}

- name: deploy tomcat
  hosts: apps
  become: yes
  roles:
    - {name: app-tier}

- name: deploy postgres
  hosts: apps
  become: yes
  roles:
    - {name: db-tier}

# Done in APP TIER
# - name: deploy apache
#   hosts: apps
#   become: yes
#   roles:
#     - {name: app-tier}
