---
- name: enable repos
  template:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: install common tools
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - httpie